name: foodshare
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  flutter_map: ^8.2.2
  geolocator: ^14.0.3
  mapbox_maps_flutter: ^2.25.0
  flutter_dotenv: ^6.0.1
  url_launcher: ^6.3.0
  http: ^1.2.0  
  

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/logo.png